import { CardProfile, CardTheme } from './types';

export const CARD_THEMES: Record<string, CardTheme> = {
  'halftone': {
    key: 'halftone',
    label: 'Halftone Cosmic',
    description: 'Dynamic violet & magenta dot grid (Air Preset)',
    category: 'Print & Pop',
    bgGradient: 'from-violet-950 via-purple-900 to-indigo-950',
    cardBg: 'linear-gradient(145deg, #1e1035, #351b5c)',
    textColor: '#f5f3ff',
    accentColor: '#c084fc',
    chipBg: 'rgba(192, 132, 252, 0.16)',
    borderColor: 'rgba(192, 132, 252, 0.35)',
    glowColor: 'rgba(168, 85, 247, 0.4)',
    swatchColors: ['#3b1e52', '#a56cd1'],
    darkBgHex: '#1e1035',
  },
  'halftone-ink': {
    key: 'halftone-ink',
    label: 'Halftone Ink',
    description: 'Deep navy & electric blue ink print (Kelindi)',
    category: 'Print & Pop',
    bgGradient: 'from-slate-950 via-indigo-950 to-blue-950',
    cardBg: 'linear-gradient(145deg, #0d1730, #192b59)',
    textColor: '#e0e7ff',
    accentColor: '#818cf8',
    chipBg: 'rgba(129, 140, 248, 0.16)',
    borderColor: 'rgba(129, 140, 248, 0.35)',
    glowColor: 'rgba(99, 102, 241, 0.4)',
    swatchColors: ['#131c38', '#6366f1'],
    darkBgHex: '#0d1730',
  },
  'wave': {
    key: 'wave',
    label: 'Liquid Ocean',
    description: 'Flowing deep cyan & ocean waves (Mark Preset)',
    category: 'Fluid',
    bgGradient: 'from-cyan-950 via-blue-900 to-sky-950',
    cardBg: 'linear-gradient(145deg, #09203f, #134e5e)',
    textColor: '#e0f2fe',
    accentColor: '#38bdf8',
    chipBg: 'rgba(56, 189, 248, 0.16)',
    borderColor: 'rgba(56, 189, 248, 0.35)',
    glowColor: 'rgba(14, 165, 233, 0.4)',
    swatchColors: ['#0a2f4a', '#3ba9e0'],
    darkBgHex: '#09203f',
  },
  'sparkle': {
    key: 'sparkle',
    label: 'Sparkle Cyan',
    description: 'Turquoise glimmer and twinkle stars (Helena Preset)',
    category: 'Glint & Star',
    bgGradient: 'from-teal-950 via-cyan-950 to-slate-900',
    cardBg: 'linear-gradient(145deg, #092630, #164e63)',
    textColor: '#ccfbf1',
    accentColor: '#5eead4',
    chipBg: 'rgba(94, 234, 212, 0.16)',
    borderColor: 'rgba(94, 234, 212, 0.35)',
    glowColor: 'rgba(20, 184, 166, 0.4)',
    swatchColors: ['#0d3b4a', '#7ee0d5'],
    darkBgHex: '#092630',
  },
  'sparkle-gold': {
    key: 'sparkle-gold',
    label: 'Sparkle Warm Gold',
    description: 'Luminous gold & amber glint particles (Carlos Preset)',
    category: 'Luxury',
    bgGradient: 'from-stone-950 via-amber-950 to-neutral-900',
    cardBg: 'linear-gradient(145deg, #1a150c, #382c16)',
    textColor: '#fef3c7',
    accentColor: '#fbbf24',
    chipBg: 'rgba(251, 191, 36, 0.16)',
    borderColor: 'rgba(251, 191, 36, 0.35)',
    glowColor: 'rgba(245, 158, 11, 0.4)',
    swatchColors: ['#3d280d', '#f59e0b'],
    darkBgHex: '#1a150c',
  },
  'dither': {
    key: 'dither',
    label: 'Cyber Dither',
    description: 'Retro Bayer matrix pixel field (Staromlynski)',
    category: 'Retro',
    bgGradient: 'from-emerald-950 via-green-950 to-teal-950',
    cardBg: 'linear-gradient(145deg, #062013, #0f4025)',
    textColor: '#ecfdf5',
    accentColor: '#34d399',
    chipBg: 'rgba(52, 211, 153, 0.16)',
    borderColor: 'rgba(52, 211, 153, 0.35)',
    glowColor: 'rgba(16, 185, 129, 0.4)',
    swatchColors: ['#0f331e', '#10b981'],
    darkBgHex: '#062013',
  },
  'ascii': {
    key: 'ascii',
    label: 'Matrix ASCII',
    description: 'Futuristic floating code stream (Liuying Preset)',
    category: 'Terminal',
    bgGradient: 'from-neutral-950 via-slate-900 to-black',
    cardBg: 'linear-gradient(145deg, #0b0f19, #172554)',
    textColor: '#f8fafc',
    accentColor: '#60a5fa',
    chipBg: 'rgba(96, 165, 250, 0.16)',
    borderColor: 'rgba(96, 165, 250, 0.35)',
    glowColor: 'rgba(59, 130, 246, 0.4)',
    swatchColors: ['#172554', '#60a5fa'],
    darkBgHex: '#0b0f19',
  },
  'holographic': {
    key: 'holographic',
    label: 'Hologram Neon',
    description: 'Vibrant chromatic magenta & cyan foil shimmer',
    category: 'Vibrant',
    bgGradient: 'from-fuchsia-950 via-purple-950 to-cyan-950',
    cardBg: 'linear-gradient(145deg, #2e0854, #501348)',
    textColor: '#fae8ff',
    accentColor: '#f472b6',
    chipBg: 'rgba(244, 114, 182, 0.18)',
    borderColor: 'rgba(244, 114, 182, 0.4)',
    glowColor: 'rgba(236, 72, 153, 0.45)',
    swatchColors: ['#4a0e4e', '#ec4899'],
    darkBgHex: '#2e0854',
  },
  'obsidian': {
    key: 'obsidian',
    label: 'Obsidian Minimal',
    description: 'Pure monochrome luxury with silver accents',
    category: 'Monochrome',
    bgGradient: 'from-neutral-950 via-zinc-900 to-stone-950',
    cardBg: 'linear-gradient(145deg, #121214, #232328)',
    textColor: '#fafafa',
    accentColor: '#e4e4e7',
    chipBg: 'rgba(255, 255, 255, 0.08)',
    borderColor: 'rgba(255, 255, 255, 0.2)',
    glowColor: 'rgba(255, 255, 255, 0.15)',
    swatchColors: ['#18181b', '#71717a'],
    darkBgHex: '#121214',
  },

  // --- OpenShaders Community Themes ---
  'prism': {
    key: 'prism',
    label: 'Chroma Prism (Shawn Chen)',
    description: '1% Ultra Rare - Refracting crystal dispersion prism',
    category: 'OpenShaders (1% Ultra Rare)',
    rarity: 'Ultra Rare',
    rarityRate: '1% Prism',
    openshadersHandle: 'shawn_chen',
    bgGradient: 'from-blue-950 via-slate-900 to-sky-950',
    cardBg: 'linear-gradient(145deg, #021226, #092c57)',
    textColor: '#e0f2fe',
    accentColor: '#38bdf8',
    chipBg: 'rgba(56, 189, 248, 0.18)',
    borderColor: 'rgba(56, 189, 248, 0.4)',
    glowColor: 'rgba(14, 165, 233, 0.5)',
    swatchColors: ['#00224c', '#008cd3'],
    darkBgHex: '#021226',
  },
  'splines': {
    key: 'splines',
    label: 'Iridescent Splines',
    description: '1% Ultra Rare - Amber & purple prismatic curve flow',
    category: 'OpenShaders (1% Ultra Rare)',
    rarity: 'Ultra Rare',
    rarityRate: '1% Prism',
    openshadersHandle: 'splines',
    bgGradient: 'from-amber-950 via-stone-900 to-rose-950',
    cardBg: 'linear-gradient(145deg, #240803, #4a1c0d)',
    textColor: '#ffedd5',
    accentColor: '#fb923c',
    chipBg: 'rgba(251, 146, 60, 0.18)',
    borderColor: 'rgba(251, 146, 60, 0.4)',
    glowColor: 'rgba(249, 115, 22, 0.5)',
    swatchColors: ['#300100', '#934500'],
    darkBgHex: '#240803',
  },
  'pixel': {
    key: 'pixel',
    label: 'Mosaic Grid (Farrel)',
    description: '4% Legendary - Warm terracotta pixel mosaic grid',
    category: 'OpenShaders (4% Legendary)',
    rarity: 'Legendary',
    rarityRate: '4% Pixel',
    openshadersHandle: 'farrel',
    bgGradient: 'from-orange-950 via-neutral-900 to-amber-950',
    cardBg: 'linear-gradient(145deg, #220803, #3f1910)',
    textColor: '#ffedd5',
    accentColor: '#f97316',
    chipBg: 'rgba(249, 115, 22, 0.16)',
    borderColor: 'rgba(249, 115, 22, 0.35)',
    glowColor: 'rgba(234, 88, 12, 0.4)',
    swatchColors: ['#2d0500', '#8f4b30'],
    darkBgHex: '#220803',
  },
  'grain': {
    key: 'grain',
    label: 'Analog Grain (Patrik)',
    description: '13% Rare - Nostalgic film grain & magenta mist',
    category: 'OpenShaders (13% Rare)',
    rarity: 'Rare',
    rarityRate: '13% Film Grain',
    openshadersHandle: 'patrik',
    bgGradient: 'from-fuchsia-950 via-neutral-900 to-pink-950',
    cardBg: 'linear-gradient(145deg, #23081e, #45173e)',
    textColor: '#fdf4ff',
    accentColor: '#e879f9',
    chipBg: 'rgba(232, 121, 249, 0.16)',
    borderColor: 'rgba(232, 121, 249, 0.35)',
    glowColor: 'rgba(217, 70, 239, 0.4)',
    swatchColors: ['#340d2d', '#a96599'],
    darkBgHex: '#23081e',
  },
  'loewe': {
    key: 'loewe',
    label: 'Velvet Matrix (Loewe)',
    description: '12% Rare - Crimson velvet matrix glyph descent',
    category: 'OpenShaders (12% Rare)',
    rarity: 'Rare',
    rarityRate: '12% ASCII',
    openshadersHandle: 'loewe',
    bgGradient: 'from-rose-950 via-stone-900 to-red-950',
    cardBg: 'linear-gradient(145deg, #270609, #4b1016)',
    textColor: '#ffe4e6',
    accentColor: '#fb7185',
    chipBg: 'rgba(251, 113, 133, 0.16)',
    borderColor: 'rgba(251, 113, 133, 0.35)',
    glowColor: 'rgba(244, 63, 94, 0.4)',
    swatchColors: ['#3f0000', '#b93f32'],
    darkBgHex: '#270609',
  },
  'javazero': {
    key: 'javazero',
    label: 'Cyber Vermilion (Javazero)',
    description: '12% Rare - Red & coral futuristic code stream',
    category: 'OpenShaders (12% Rare)',
    rarity: 'Rare',
    rarityRate: '12% ASCII',
    openshadersHandle: 'javazero',
    bgGradient: 'from-red-950 via-zinc-900 to-rose-950',
    cardBg: 'linear-gradient(145deg, #2b060d, #52121e)',
    textColor: '#ffe4e6',
    accentColor: '#f43f5e',
    chipBg: 'rgba(244, 63, 94, 0.16)',
    borderColor: 'rgba(244, 63, 94, 0.35)',
    glowColor: 'rgba(225, 29, 72, 0.4)',
    swatchColors: ['#40000b', '#bf525b'],
    darkBgHex: '#2b060d',
  },
  'banhua': {
    key: 'banhua',
    label: 'Blossom Aurora (Banhua)',
    description: 'Hypnotic lavender & indigo fluid surface',
    category: 'OpenShaders Explore',
    rarity: 'Common',
    rarityRate: '39% Fluid',
    openshadersHandle: 'banhua',
    bgGradient: 'from-indigo-950 via-slate-900 to-purple-950',
    cardBg: 'linear-gradient(145deg, #110e30, #221c57)',
    textColor: '#e0e7ff',
    accentColor: '#818cf8',
    chipBg: 'rgba(129, 140, 248, 0.16)',
    borderColor: 'rgba(129, 140, 248, 0.35)',
    glowColor: 'rgba(99, 102, 241, 0.4)',
    swatchColors: ['#191745', '#7277c6'],
    darkBgHex: '#110e30',
  },
  'cyrsks': {
    key: 'cyrsks',
    label: 'Deep Sapphire (Cyrsks)',
    description: 'Emerald depths & rich cyan fluid field',
    category: 'OpenShaders Explore',
    rarity: 'Common',
    rarityRate: '39% Fluid',
    openshadersHandle: 'cyrsks',
    bgGradient: 'from-teal-950 via-slate-900 to-emerald-950',
    cardBg: 'linear-gradient(145deg, #021a1a, #073837)',
    textColor: '#ccfbf1',
    accentColor: '#2dd4bf',
    chipBg: 'rgba(45, 212, 191, 0.16)',
    borderColor: 'rgba(45, 212, 191, 0.35)',
    glowColor: 'rgba(20, 184, 166, 0.4)',
    swatchColors: ['#002a29', '#009491'],
    darkBgHex: '#021a1a',
  },
  'orcdev': {
    key: 'orcdev',
    label: 'Emerald Pulse (Orcdev)',
    description: '13% Rare - Matrix emerald grain & pulse field',
    category: 'OpenShaders Creator',
    rarity: 'Rare',
    rarityRate: '13% Grain',
    openshadersHandle: 'orcdev',
    bgGradient: 'from-green-950 via-neutral-900 to-emerald-950',
    cardBg: 'linear-gradient(145deg, #021706, #093311)',
    textColor: '#dcfce7',
    accentColor: '#22c55e',
    chipBg: 'rgba(34, 197, 94, 0.16)',
    borderColor: 'rgba(34, 197, 94, 0.35)',
    glowColor: 'rgba(22, 163, 74, 0.4)',
    swatchColors: ['#002000', '#007622'],
    darkBgHex: '#021706',
  },
  'clio': {
    key: 'clio',
    label: 'Solar Amber (Clio)',
    description: '10% Rare - Cobalt & amber solar dither field',
    category: 'OpenShaders (10% Rare)',
    rarity: 'Rare',
    rarityRate: '10% Dither',
    openshadersHandle: 'clio',
    bgGradient: 'from-blue-950 via-slate-900 to-indigo-950',
    cardBg: 'linear-gradient(145deg, #07112d, #142352)',
    textColor: '#dbeafe',
    accentColor: '#60a5fa',
    chipBg: 'rgba(96, 165, 250, 0.16)',
    borderColor: 'rgba(96, 165, 250, 0.35)',
    glowColor: 'rgba(37, 99, 235, 0.4)',
    swatchColors: ['#0c1b4b', '#5f7fd1'],
    darkBgHex: '#07112d',
  },
};

export function getCardTheme(themeKey: string): CardTheme {
  const existingTheme = CARD_THEMES[themeKey];
  if (existingTheme) return existingTheme;

  const seed = [...themeKey].reduce((total, character) => total + character.charCodeAt(0), 0);
  const palettes = [
    ['#17102d', '#7c3aed', '#c4b5fd'],
    ['#071f2c', '#0891b2', '#67e8f9'],
    ['#26120a', '#ea580c', '#fdba74'],
    ['#101c18', '#059669', '#6ee7b7'],
  ] as const;
  const palette = palettes[seed % palettes.length];

  return {
    key: themeKey,
    label: `Custom Shader: @${themeKey}`,
    description: 'A generated shader theme for your handle',
    category: 'Custom Shader',
    bgGradient: 'from-neutral-950 via-slate-900 to-violet-950',
    cardBg: `linear-gradient(145deg, ${palette[0]}, ${palette[1]}88)`,
    textColor: '#f8fafc',
    accentColor: palette[2],
    chipBg: `${palette[1]}29`,
    borderColor: `${palette[2]}66`,
    glowColor: `${palette[1]}80`,
    swatchColors: [palette[0], palette[1]],
    darkBgHex: palette[0],
    isCustomOpenShader: true,
  };
}

export const DEFAULT_PROFILE: CardProfile = {
  name: 'Alex Rivera',
  username: 'alexrivera',
  role: 'Software Engineer & Creator',
  location: 'San Francisco, CA',
  year: '2026',
  bio: 'Designing interactive web worlds, generative graphics, and developer tools.',
  avatar: '',
  skills: ['TypeScript', 'React', 'WebGPU', 'Shaders', 'Next.js'],
  badges: ['Software Engineer', 'Verified Creator'],
  links: {
    website: 'https://alexrivera.dev',
    github: 'https://github.com/alexrivera',
    x: 'https://x.com/alexrivera',
    discord: 'alex#0001',
    linkedin: 'https://linkedin.com',
  },
  themeKey: 'holographic',
  show: {
    username: true,
    location: true,
    year: true,
    bio: true,
    links: true,
    skills: true,
    badges: true,
    qr: false,
    showSkillsOnFront: false,
    showLinksOnFront: false,
    showStatusOnFront: true,
    showClockOnFront: false,
    showMottoOnBack: true,
    showProjectOnBack: true,
  },
  material: {
    finish: 'holographic',
    shimmerIntensity: 65,
    glassBlur: 14,
    borderRadius: 'rounded-2xl',
  },
  typography: {
    fontFamily: 'sans',
    layoutPreset: 'balanced',
  },
  status: {
    status: 'available',
    customText: 'Available for Projects',
    showClock: false,
    cityLabel: 'San Francisco',
  },
  avatarConfig: {
    type: 'monogram',
    shape: 'squircle',
    glowRing: true,
  },
  showcase: {
    motto: 'Crafting digital experiences at the intersection of design and code.',
    projectTitle: 'Neon Odyssey',
    projectDesc: 'Atmospheric WebGPU experience with real-time procedural shaders.',
    projectUrl: 'https://alexrivera.dev/games/neon',
    email: 'contact@alexrivera.dev',
  },
};

export const MATERIAL_PRESETS = [
  {
    id: 'holographic',
    label: 'Holographic Foil',
    desc: 'Prismatic rainbow shimmer that moves with your cursor',
    icon: 'Sparkles',
  },
  {
    id: 'glass',
    label: 'Frosted Glass',
    desc: 'Translucent frosted acrylic with ambient background blur',
    icon: 'Eye',
  },
  {
    id: 'metallic',
    label: 'Brushed Metal',
    desc: 'Reflective chrome sheen with sharp edge highlights',
    icon: 'Shield',
  },
  {
    id: 'matte',
    label: 'Obsidian Matte',
    desc: 'Deep light-absorbing velvet matte with silver details',
    icon: 'Moon',
  },
] as const;

export const FONT_PRESETS = [
  {
    id: 'sans',
    label: 'Modern Sans',
    sublabel: 'Clean & Balanced',
    fontClass: 'font-sans',
    sample: 'AaBb 123',
  },
  {
    id: 'mono',
    label: 'Developer Mono',
    sublabel: 'Terminal & Code',
    fontClass: 'font-mono',
    sample: '<Dev/> 01',
  },
  {
    id: 'serif',
    label: 'Luxury Serif',
    sublabel: 'Editorial & Classic',
    fontClass: 'font-serif',
    sample: 'Élite 1926',
  },
  {
    id: 'cyber',
    label: 'Cyber Display',
    sublabel: 'Futuristic Grid',
    fontClass: 'font-mono tracking-wider uppercase',
    sample: 'SYS//99',
  },
] as const;

export const LAYOUT_PRESETS = [
  {
    id: 'balanced',
    label: 'Balanced Card',
    desc: 'Standard digital card with clean hierarchy',
  },
  {
    id: 'minimal',
    label: 'Ultra Minimal',
    desc: 'Focus purely on name, title, and monogram',
  },
  {
    id: 'developer',
    label: 'Developer Centric',
    desc: 'Code badge highlights and terminal accents',
  },
  {
    id: 'showcase',
    label: 'Showcase & Creator',
    desc: 'Live status and manifesto emphasis',
  },
] as const;

export const STATUS_PRESETS = [
  { id: 'available', label: 'Available for Work', color: 'bg-emerald-500', text: 'text-emerald-400' },
  { id: 'focus', label: 'In Focus Mode', color: 'bg-amber-500', text: 'text-amber-400' },
  { id: 'busy', label: 'Coding / Busy', color: 'bg-rose-500', text: 'text-rose-400' },
  { id: 'gaming', label: 'Testing / Play', color: 'bg-purple-500', text: 'text-purple-400' },
  { id: 'none', label: 'Hidden (Off)', color: 'bg-neutral-600', text: 'text-neutral-400' },
] as const;

export const PRESET_BADGES = [
  'Software Engineer',
  'Verified Creator',
  'Indie Builder',
  'UI/UX Designer',
  'Game Dev',
  '3D Artist',
  'Full Stack',
  'AI Explorer',
  'Founder',
  'Gamer',
  'Student',
  'Open Source',
];

export const PRESET_SKILLS = [
  'TypeScript',
  'JavaScript',
  'React',
  'Next.js',
  'WebGPU',
  'Shaders',
  'Node.js',
  'Python',
  'Tailwind CSS',
  'Game Development',
  'Unity',
  'Blender',
  '3D Modeling',
  'UI/UX Design',
  'Figma',
  'C#',
  'Rust',
  'Go',
];

export const SAMPLE_EXPLORE_PROFILES: CardProfile[] = [
  {
    name: 'Alex Rivera',
    username: 'alexcode',
    role: 'Graphics & Engine Dev',
    location: 'San Francisco, CA',
    year: '2026',
    bio: 'Real-time ray tracing, WebGPU experiments, and creative shaders.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    skills: ['WebGPU', 'Shaders', 'C++', 'Vulkan', 'TypeScript'],
    badges: ['Software Engineer', 'AI Explorer'],
    links: { github: 'https://github.com', website: 'https://alex.graphics' },
    themeKey: 'holographic',
    show: {
      username: true,
      location: true,
      year: true,
      bio: true,
      links: true,
      skills: true,
      badges: true,
      qr: true,
      showSkillsOnFront: false,
      showLinksOnFront: false,
    },
  },
  {
    name: 'Maya Chen',
    username: 'mayachen',
    role: 'Lead UI/UX Designer',
    location: 'Tokyo, JP',
    year: '2025',
    bio: 'Crafting spatial interfaces and digital design systems.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    skills: ['Design Systems', 'Figma', 'Prototyping', '3D UI'],
    badges: ['UI/UX Designer', 'Verified Creator'],
    links: { website: 'https://maya.design', x: 'https://x.com' },
    themeKey: 'holographic',
    show: {
      username: true,
      location: true,
      year: true,
      bio: true,
      links: true,
      skills: true,
      badges: true,
      qr: true,
      showSkillsOnFront: false,
      showLinksOnFront: false,
    },
  },
  {
    name: 'Elena Rostova',
    username: 'elenart',
    role: '3D Artist & Animator',
    location: 'Berlin, DE',
    year: '2026',
    bio: 'Character modeling, low-poly environments, and visual effects.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    skills: ['Blender', 'Substance', 'Animation', 'Character Art'],
    badges: ['3D Artist', 'Indie Studio'],
    links: { website: 'https://elena.art', discord: 'elena#1234' },
    themeKey: 'sparkle-gold',
    show: {
      username: true,
      location: true,
      year: true,
      bio: true,
      links: true,
      skills: true,
      badges: true,
      qr: true,
      showSkillsOnFront: false,
      showLinksOnFront: false,
    },
  },
];
